### ISSUE TITLE
Add Tags for Released version's.

### ISSUE THREAD

**Issue by cmdorexe** [polter-rnd/far2l-rpm#1]
Прошу добавить теги к выпускаемым версиям, для контроля версий.

**Comment by icesvz** [comment]
@polter-rnd  мне кажется норм, стоит сделать,  как то так получается  https://github.com/icesvz/far2l-rpm/releases/tag/2.6.0-beta-3a39598  

_хотя, конечно, сейчас распространять архивы стало немного немодно_

**Comment by polter-rnd** [comment]
Добавил, начиная с 2.6.1
